feat: integrate docsearch with algolia
razor-network/docs-v2 pull request #132
Opened 2024-06-25 05:57 UTC by rajkharvar

2024-06-25 07:05 UTC, yohanelly95 requested changes

2024-06-25 07:05 UTC, yohanelly95 commented on docusaurus.config.js
> +        apiKey: "0170bec8ff2a904d2ff209bbacab9f96",
can you make this private @rajkharvar

2024-06-25 07:10 UTC, rajkharvar commented on docusaurus.config.js
> +        apiKey: "0170bec8ff2a904d2ff209bbacab9f96",
As per algolia, it's fine we can keep the api key public
https://support.algolia.com/hc/en-us/articles/8150525164049-Can-I-set-up-DocSearch-Github-secrets
https://support.algolia.com/hc/en-us/articles/18966776061329-Can-the-search-API-key-be-public

2024-06-25 07:37 UTC, yohanelly95 approved these changes

2024-06-25 09:03 UTC, ashish10677 requested changes

2024-06-25 09:03 UTC, ashish10677 commented on docusaurus.config.js
> +        // externalUrlRegex: 'external\\.com|domain\\.com',
Can you remove these if not required

2024-06-25 09:03 UTC, ashish10677 commented on docusaurus.config.js
> +          //   {
Why are these commented? If not required remove.

2024-06-25 09:13 UTC, rajkharvar commented on docusaurus.config.js
> +        // externalUrlRegex: 'external\\.com|domain\\.com',
Fixed in [e8499ad](https://github.com/razor-network/docs-v2/pull/132/commits/e8499addc3585d017da10b0de1d9d18d6a00eef6)

2024-06-25 09:14 UTC, rajkharvar commented on docusaurus.config.js
> +          //   {
Removed [e8499ad](https://github.com/razor-network/docs-v2/pull/132/commits/e8499addc3585d017da10b0de1d9d18d6a00eef6)

2024-06-26 06:29 UTC, ashish10677 approved these changes

2024-06-26 06:31 UTC, merged