updated docs for oracle-node v1.0.5 release
razor-network/docs-v2 pull request #76
Opened 2022-11-17 10:24 UTC by Shrikant1212

Fixes #64

2022-11-21 11:26 UTC, yohanelly95 approved these changes

2022-11-24 13:48 UTC, Yashk767 commented
Merge it only after `v1.0.5` (Public release) is released.
It's raised right now in order to help internal validators use updated commands for `v1.0.5-beta`(internal prod release).
@yohanelly95  @rajkharvar

2022-11-24 13:50 UTC, Yashk767 requested changes

2022-11-24 13:50 UTC, Yashk767 commented on docs/stake/testnet.md
> +- RPC Timeout: This is the threshold number of seconds after which any contract and client calls will time out.
can you change this to 
```
RPC Timeout: Number of seconds after which any contract and client calls will time out if it's not responding
```

2022-12-02 07:45 UTC, Yashk767 commented
https://deploy-preview-76--razor-docs-v2.netlify.app/docs/stake/mainnet#software-dependencies
Here the docker image url needs to be updated with v1.0.5 docker image url which we would get once it is released.

Just reminding, you can merge it after this change is done. @yohanelly95 @rajkharvar

2022-12-14 11:39 UTC, SkandaBhat approved these changes

2022-12-14 11:40 UTC, yohanelly95 approved these changes

2022-12-14 11:41 UTC, SkandaBhat commented on docs/stake/testnet.md
> +Razor-Go(github): You can download the Razor-go:v1.0.5-alpha from [here](https://github.com/razor-network/oracle-node/releases/tag/v1.0.5-alpha-patch2).
This is correct.

2022-12-14 11:41 UTC, merged