Docs for consuming datafeeds via Transparent Forwarder
razor-network/docs-v2 pull request #81
Opened 2022-12-20 05:29 UTC by rajkharvar

fixes #78

2022-12-21 06:49 UTC, yohanelly95 requested changes

2022-12-21 06:49 UTC, yohanelly95 commented on docs/data-feeds/consuming-data-feeds.md
> +**Note**: For **staging-utter-unripe-menkar** chain it's required to to reference `ITransparentForwarder` instead of `IResultManager` due to distinct bridging architecture.
typo here, `to to`

2022-12-21 07:01 UTC, rajkharvar commented on docs/data-feeds/consuming-data-feeds.md
> +**Note**: For **staging-utter-unripe-menkar** chain it's required to to reference `ITransparentForwarder` instead of `IResultManager` due to distinct bridging architecture.
resolved in [e6e89b4](https://github.com/razor-network/docs-v2/pull/81/commits/e6e89b40fe25d0d2efa886d30a78218a010d8cb0)

2022-12-23 10:23 UTC, SamAg19 approved these changes

2022-12-23 10:33 UTC, merged