Add section for adding datasource through proposal
razor-network/docs-v2 pull request #98
Opened 2023-08-02 08:40 UTC by rajkharvar

2023-08-28 06:49 UTC, SkandaBhat approved these changes

2023-08-28 06:55 UTC, SkandaBhat commented on docs/Governance.md
> +2. Next, make the necessary changes to the forked repository, incorporating the required information based on the `contributing.md` guidelines and project requirements. Once you have completed the ch
Lnk the contributing.md here.

2023-08-28 06:55 UTC, SkandaBhat requested changes
link contrib link in the governance docs.

2023-09-01 08:50 UTC, rajkharvar commented on docs/Governance.md
> +2. Next, make the necessary changes to the forked repository, incorporating the required information based on the `contributing.md` guidelines and project requirements. Once you have completed the ch
Resolved in [9597677](https://github.com/razor-network/docs-v2/pull/98/commits/95976779341b3f092b4245a4b20c5ad5afa381bf)

2023-09-07 07:50 UTC, yohanelly95 commented on docs/Governance.md
> +1. Acception or Rejection of Data sources collections.
Acceptance* small typo @rajkharvar

2023-09-11 11:45 UTC, SkandaBhat commented on docs/Governance.md
> +The Razor Network governance portal can be accessed [here](https://vote.razor.network/). You need to hold $RAZOR tokens on Ethereum/Polygon Mainnet or $sRZR (staked $RAZOR tokens) on Razor SKALE Chai
Add it in a new line starting with "NOTE:..."

2023-09-11 12:01 UTC, hrishikeshio commented on docs/Governance.md
> +It is quite important to whitelist or backlist the data sources to prevent any misinformation and DoS attacks.
make it add or remove data sources. we dont have blacklist.

2023-09-11 12:04 UTC, rajkharvar commented on docs/Governance.md
> +It is quite important to whitelist or backlist the data sources to prevent any misinformation and DoS attacks.
Resolved [22d444b](https://github.com/razor-network/docs-v2/pull/98/commits/22d444b5b3e609169a7046b19b24e12ee63bc153)

2023-09-11 12:46 UTC, merged